version: '3'


services:

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: lovelgeorge/blog_backend
    
    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app

  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: lovelgeorge/blog_frontend

    ports:
      - '3000:3000'

    volumes:
      - ./frontend:/app

    depends_on:
      - backend
