export const BLOG_LIST_REQUEST='BLOG_LIST_REQUEST'
export const BLOG_LIST_SUCCESS='BLOG_LIST_SUCCESS'
export const BLOG_LIST_FAIL='BLOG_LIST_FAIL'


export const BLOG_CONTENT_REQUEST='BLOG_CONTENT_REQUEST'
export const BLOG_CONTENT_SUCCESS='BLOG_CONTENT_SUCCESS'
export const BLOG_CONTENT_FAIL='BLOG_CONTENT_FAIL'
