# Generated by Django 4.1.6 on 2023-02-20 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.blog'),
        ),
    ]
