# Generated by Django 4.1.6 on 2023-02-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='title',
        ),
    ]
