# Generated by Django 4.1.6 on 2023-02-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_content_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='titleImage',
        ),
    ]
